from library_for_lc import *
class Solution(object):
    @timeit
    def longestCommonSubsequence(self, t1, t2):
        """
        :type t1: str
        :type t2: str
        :rtype: int
        """
        m,n = len(t1), len(t2)
        p = [0]*(n+1)
        for i in range(m):
            c = [0]*(n+1)
            for j in range(n):
                if t1[i] == t2[j]: c[j+1] = 1 + p[j]
                else: c[j+1] = c[j] if c[j] > p[j+1] else  p[j+1]
            p = c
        return c[n]

#print Solution().longestCommonSubsequence("abcde", "ace" )
#print Solution().longestCommonSubsequence("abc", "abc" )
#print Solution().longestCommonSubsequence("abc", "def")
print (Solution().longestCommonSubsequence("AGGTAB", "GXTXAYB"))
print (Solution().longestCommonSubsequence("kdersnafojqjijwjgraxodkhmnajyxgnqdmxkpaxufwxujetancparypkhqdmvarexcpezajwjwfovyjejwnupuhgrixepkzmvahojmjyrglufkfapcbefqrwnuxcpqfunydmpmnkpatipajudwhwjstwjglmvsdcpyrmfkpsrorapylatshgvuhyzwbwfalybuvupubihyrwbyzyfqrofofyfyjehozobafoxadozwfirajwzonulkbwtoxcbgnidgduryhohapohwhglalktcxsnwnuxszevyxcbilgzsxclchiputqlsluryvydstgzszehsjafizwxgbqpmzanitobojknctonylcvwnovqbozmnwfqxyrsnovghanobiralwnejapwvwrqlcpqvuhyrshynifmtuzqzsdyxevunifkzmzcfafsnilixgdwtchehuhwvotyhwdurkxoheparybwnutmbsxqxkhaludodinmdgtkvqzgtglefmrktylclmbcfulgvkningnszirezgvyfexstohqpqjizuxyzgtstipgvshynufaraxinadsjwjoxcxezkxopmxobmrcbydynohifczsvspoxmhwxcxefgvynkpkzahglqxkjiropynczwnwvcfklufkzufmbshazuzijklqtkdmzktcngrefsnsdqbejazinkbejaxwtcdoberqfmzgvglefgnsxmdulavonmxynungvixahonyzafatazilyxozoludmtczedevibityjybmzkpohopojylefexgzuvwxyxmzmjojszurunshytszcvonihelmnovghatmhqruvwpyxafyzclaxidalcjytmlivalgfqnotiturkrwpezsfihklctyxwnmvgzcbabmvqlepgpkxencxczujqxeponurozmzopmtovmlcfitkrebmpshwpal", "cvclaxqpexohcnkdknmpgdexczsvqvuzahcjuvopizkrmxgrwvctmpivkvmrwvyxuzqpshinsfsbunkzodobidklmncnovgnuzsnspijolcdypkfopqnghkpizitgzotgpcnidyjwrexspiryfstupelsnyzopizincbgravalwxuxafqnkbkzcfsdajebeduvyrqdwnuhozwrexobwjefytszslibkjcnwjaxitgdwrgtwtaxajwnorcpulkrczejcfcnijctqtwdyxunsdqzijgfydmlmvulslkjwrqvozkdslijufqbsngnujsnevmxurctwtobolgbazmtcputgrepurwfglgxetupqrsnkxijijwzktctormjgvmtyzclsxczgvejenalefqtofqjmdypybyrufktmlknqnijuvqhcbidqpsruvwnizofifelazkfynkvudynkzmjynklozarmbcxstabchmfwjcrunstedwdkbopazwxwtavupcbubyjifqnclkpahgxurqtsbkduxonenktgdcjozgzqjuvehilgbczqdyvkbcjmvytmlaxmdyvwjkrahiribcfihgbgbkbsxkdgjarmbyvgrmperizmbqlohkjenohejalkhufuzkfobqngtkbkhirybirmhobsvarerobcdqzwfmzebmrkdqlobanspefgdutipwjwpalezwrgxezcjehoradmpcryrirmzalahalcnahsdcpedizkzgzavwvixupsrihqhsdgfsvwfahchklmjcxipslofwtcbshkdshorsdgfylaratsxmtghctyfabklgfcfatutonkrghyrcrwhibadwxwzgxufilovgjunorcvmnktwjuxyrmnipcterwnuvwjgpkvodohilonwtgtufalcpojspwdidifchszitqxarenynirudcjoradibcje"))
print (Solution().longestCommonSubsequence("ypajelglgnonmvwvgjqhedczqhyjmnmbsfshanmfwdohahmpihcfupahwpgxcpebgxqtmhapszgfkpwjgzwpkdmtglczijetabujcnkpyluzclofwhajstynczsnsfengrmdcrwhahqrczwfozilsnkjyvwlcdoxcnghwxurcjqdipwfidcfcrodazgrypmxetklmxejenabgxezyvivybyjgdixypenexwhmjkvcbclqtmhmfwvmdkfkpubaxqxmdatcxutaborermdspwrqpspupaxwhobkzodmludmtspwjapcrgxwfidupadedqvujadenupyfstmbyfcropwrgxkxoxivgnqfctyzotshkbabuvmhshcbelexanmzcxihalkbslcnobknwnudutarubifodklmdwnsnsjkbebudujupwzifmlqrcpcxspyvqngvyhgtajmdkfsrwvulkxetwhetuhcpcrqvcbofmvafgtghslcbahcxalgfixytajotsfmpynstevwpkhotynqfavwfwforgbmluhmfqvqvyzwjkrcjajglstshkrcpmpwrmdwpivavejczgrazszezcbelmvilqlmfcvmpubcxqtchwxkhinkzmpovenwrqbilqjsdexazyxuvadkfcrsbqfglyjunejgnahmzqbupebwjqdyrsnkfqvszmdmdqdsrgbqhcpwzsxebujqpcpozufozupapefozkpulqrifwnincjodwryvodmlerojqfwjsbutqbolwtsdohipuzylutefsjapufyjklafwzoxynehojglupuxmjitiryfopylkpsbctkhybsngjgvensvuzqnwbufadsxwzilqlctanihczqdctqjknepclehercxyfkzmdapevsfylwrcnihuxwzuvizarapctgnutofqladwbonsjsj", "wjylwnmraxclopelilkdyvmjwpmpsnsfabgnujyjafqfcvqnspsdcjgfufelqnytwrovclqzwlqjwburqxsvehupgbgxynsvcxofefehyfknylmrqpyvotobinynobizongncnsdwxsrmdkbchanslunwjqfyhgzwzujezwvytejixgjajupkdkbejgbatinsrufsbmdurchazipyvkfkretcnunobwdefolyvyhujavgpcbmjutsbwrabcnanergfmjcvqtslefojcjgbgjspupyzanopshofexwzgrctkfctglslqhspglutqhwhgjytcnexevglapsrchuzgjcxulkxorazejilwdcxytmbgpgtirovshydmhklelivinkhuxudgnopqxqlangraxsvspcnwdcrclefotujqlgfivizcjcnotylkxwhefqdgfcdubctcjwpknmvylkbozclkbmrypcbwtchybczctsjchapobifqdyncjafwdwjcvczozefklafsvwvupixcdevwtydkrcfuxmdqburytcjwvqbqjghklmvmzqlazyvmrohodqrovszubavelidovczwpgfwfkdgpyfsbgdejopyzmnglohknwzyrgbijglsnqvmfytyhwxuzszebchgvgtmdyxwjgncjwhqrmrmtyvcxulubajgbadcncfopmfofgdezczgdalsdurkxwrglqzelgpmfudihcnsvqfcrkfepipwdmnmbinmtyputozodsdqbczixwdwzgpqnehatadylqlsbmvstaluhmxwbgdalmhmvspmzkxgfqvihsrwfgfsvqnuvmxubyvuvwfchgxkxslgzwjkzmrybqbwzatmvcrobcjyhsdejmvexqhaxqjqhexyhuhedqvcnepijczsherunmfejmferuxarctmdixgtunibstyjy"))
